### ISSUE TITLE
createEventInteractively on Android save a wrong time

### ISSUE THREAD

**Issue by elbidone** [EddyVerbruggen/Calendar-PhoneGap-Plugin#313]
I've tested the latest version, 4.5.1, It works well on iOS but creating event interactively on Android unexpectedly convert time to a wrong value. So if I want to save 9:00 AM at GMT -2 it saves 7:00 AM.
I think it should be related to following commit by @Freundschaft 
https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/commit/64e50f6eaf7f4a14c985b392edd45f84d7a42767

I've also tested using the example of README.md of this project

``` javascript
var startDate = new Date(2015,2,15,18,30,0,0,0); // beware: month 0 = january, 11 = december
var endDate = new Date(2015,2,15,19,30,0,0,0);
```

And it saves on Android the event with start_date=15h30 instead of 18h30 as expected.
Works well on iOS.

There's no mention on doc about Timezone support or conversion. **I think it should be managed by App and not the plugin**. User should be able to choose on App its preferred timezone.

**Comment by swaheed2** [comment]
same problem on for me on Android:

var startDate = new Date("2016-02-04T04:53:54.774Z");  // 10:53 pm cst
var endDate   = new Date("2016-05-01T03:51:00.000Z"); //  10:51 pm cst

Printing dates in console 
Wed Feb 03 2016 22:53:54 GMT-0600 (Central Standard Time)
Sat Apr 30 2016 22:51:00 GMT-0500 (Central Daylight Time)

Result (off by 4 hours):

![screenshot_20160810-203333](https://cloud.githubusercontent.com/assets/8592912/17576048/7e195024-5f34-11e6-95d5-ef05614aa1bb.png)

**Comment by Freundschaft** [comment]
I'm going to submit a PR later today that should fix the issue, see https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/pull/305#issuecomment-237696982

**Comment by scurker** [comment]
Any updates on this? We're still experiencing this issue with v4.5.5 and an a Google Nexus 6.

```
var startTime = new Date(2016, 11, 13, 9, 30); // Tue Dec 13 2016 09:30:00 GMT-600 (CST)
var endTime = new Date(2016, 11, 13, 10, 30); // Tue Dec 13 2016 10:30:00 GMT-600 (CST)
var endDate = new Date(2016, 11, 27); // Tue Dec 27 2016 00:00:00 GMT-600 (CST)

calendar.createEventInteractivelyWithOptions(
    "title",
    "location",
    "notes",
    startTime,
    endTime,
    { 
      recurrence: 'weekly', 
      recurrenceEndDate: endDate, 
      interval: 1 
    }
);
```

![android-nexus-6-calendar](https://cloud.githubusercontent.com/assets/1062039/21153622/ec190dfe-c130-11e6-9330-46962a1329db.png)

It would appear it's a regression in this commit: ff5e4fae094004624511e3f4145f19d98e40cf4a

**Comment by scurker** [comment]
It would appear this issue was resolved with ff5e4fae094004624511e3f4145f19d98e40cf4a
